# Generated by Django 2.0.7 on 2018-07-27 10:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_auto_20180727_1042'),
    ]

    operations = [
        migrations.RenameField(
            model_name='banner',
            old_name='imag_url',
            new_name='image_url',
        ),
    ]
